# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Finding my Glühbirnen
email: 
description: > # this means to ignore newlines until "baseurl:"
  Hi y'all! My name is Loren, and I am a junior Rails developer. 
  This space is for me to document my lessons learned, struggles, and wins as a junior dev. Happy Reading! :) 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: LCrawfish
github_username:  Locrawfish

# Build settings
markdown: kramdown
